/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: u9Csb263Bye1HhjWcckD66
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsz0NDfluKVi4F } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Z0nDfluKVi4f/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsz0NDfluKVi4F
});
