/**
 * Chat AI Sidebar Component
 * 
 * Provides real-time AI insights and tools for mediators during chat sessions:
 * - Current session tone analysis
 * - Risk assessment
 * - Quick rephrase suggestions
 * - Compact insights display
 */

import React, { useState, useEffect, useCallback } from 'react';
import { useAI } from '../../lib/useAI';
import AIInsightsDashboard from './AIInsightsDashboard';
import { apiFetch } from '../../lib/apiClient';

// Risk level indicator component
function RiskIndicator({ level, score }) {
  const getRiskColor = (level) => {
    switch (level?.toLowerCase()) {
      case 'low': return 'text-green-600 bg-green-100';
      case 'medium': return 'text-yellow-600 bg-yellow-100';
      case 'high': return 'text-red-600 bg-red-100';
      case 'critical': return 'text-red-800 bg-red-200';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  return (
    <div className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getRiskColor(level)}`}>
      {level?.toUpperCase()} ({score}/10)
    </div>
  );
}

// Tone indicator component
function ToneIndicator({ tone, intensity }) {
  const getToneColor = (tone, intensity) => {
    if (intensity >= 8) return 'text-red-600 bg-red-100';
    if (intensity >= 6) return 'text-orange-600 bg-orange-100';
    if (intensity >= 4) return 'text-yellow-600 bg-yellow-100';
    return 'text-green-600 bg-green-100';
  };

  return (
    <div className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getToneColor(tone, intensity)}`}>
      {tone} ({intensity}/10)
    </div>
  );
}

export default function ChatAISidebar({ caseId, messages = [], currentUser, isVisible = true }) {
  const [currentTone, setCurrentTone] = useState(null);
  const [currentRisk, setCurrentRisk] = useState(null);
  const [analysisLoading, setAnalysisLoading] = useState(false);
  const [rephraseText, setRephraseText] = useState('');
  const [rephraseSuggestion, setRephraseSuggestion] = useState(null);
  const [autoInsights, setAutoInsights] = useState([]);
  const [lastInsightTime, setLastInsightTime] = useState(null);
  const [showHighRiskAlert, setShowHighRiskAlert] = useState(false);

  const { analyzeTone, assessRisk, suggestRephrase, loading, error } = useAI();

  // Analyze recent messages for tone and risk
  const analyzeRecentMessages = useCallback(async () => {
    if (!messages.length || analysisLoading) return;

    // Get last 5 messages for analysis
    const recentMessages = messages.slice(-5);
    const conversationText = recentMessages
      .map(msg => `[${msg.sender_role}]: ${msg.content}`)
      .join('\n');

    if (conversationText.trim().length < 10) return;

    setAnalysisLoading(true);

    try {
      // Analyze tone of the latest message
      const latestMessage = recentMessages[recentMessages.length - 1];
      if (latestMessage && latestMessage.content) {
        const toneResult = await analyzeTone(
          latestMessage.content,
          latestMessage.sender_role,
          caseId,
          false // Don't save individual message analysis
        );
        setCurrentTone(toneResult.analysis);
      }

      // Assess escalation risk for the conversation
      const riskResult = await assessRisk(conversationText, caseId, false);
      setCurrentRisk(riskResult.assessment);

    } catch (err) {
      console.error('Failed to analyze messages:', err);
    } finally {
      setAnalysisLoading(false);
    }
  }, [messages, analyzeTone, assessRisk, caseId, analysisLoading]);

  // Auto-analyze when new messages arrive
  useEffect(() => {
    if (messages.length > 0) {
      const timeoutId = setTimeout(analyzeRecentMessages, 1000); // Debounce
      return () => clearTimeout(timeoutId);
    }
  }, [messages, analyzeRecentMessages]);

  // Poll for new auto-generated AI insights
  useEffect(() => {
    if (!caseId) return;

    const fetchInsights = async () => {
      try {
        const response = await apiFetch(`/api/ai/insights/${caseId}?limit=10`);
        if (response.ok && response.data?.insights) {
          // Filter to only auto-generated insights
          const autoGenerated = response.data.insights.filter(
            insight => insight.metadata?.auto_generated === true
          );
          
          setAutoInsights(autoGenerated);

          // Check for new high-risk insights
          if (autoGenerated.length > 0) {
            const latestInsight = autoGenerated[0];
            const isNew = !lastInsightTime || new Date(latestInsight.created_at) > lastInsightTime;
            
            if (isNew) {
              setLastInsightTime(new Date(latestInsight.created_at));
              
              // Show alert if high risk
              if (latestInsight.insight_type === 'risk_assessment') {
                const riskLevel = latestInsight.content?.risk_level;
                if (riskLevel === 'high' || riskLevel === 'critical') {
                  setShowHighRiskAlert(true);
                  setCurrentRisk(latestInsight.content);
                  
                  // Auto-hide alert after 10 seconds
                  setTimeout(() => setShowHighRiskAlert(false), 10000);
                }
              }
              
              // Update current tone from latest auto-generated tone analysis
              if (latestInsight.insight_type === 'tone_analysis') {
                setCurrentTone(latestInsight.content);
              }
            }
          }
        }
      } catch (err) {
        console.error('Failed to fetch AI insights:', err);
      }
    };

    // Initial fetch
    fetchInsights();

    // Poll every 5 seconds
    const intervalId = setInterval(fetchInsights, 5000);

    return () => clearInterval(intervalId);
  }, [caseId, lastInsightTime]);

  // Handle rephrase suggestion
  const handleRephraseRequest = async () => {
    if (!rephraseText.trim()) return;

    try {
      const result = await suggestRephrase(rephraseText, 'maintain neutral tone', caseId, false);
      setRephraseSuggestion(result.suggestion);
    } catch (err) {
      console.error('Failed to get rephrase suggestion:', err);
    }
  };

  const handleUseSuggestion = () => {
    if (rephraseSuggestion?.suggested) {
      setRephraseText(rephraseSuggestion.suggested);
      setRephraseSuggestion(null);
    }
  };

  if (!isVisible) return null;

  return (
    <div className="w-80 bg-white border-l border-gray-200 flex flex-col">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 bg-gray-50">
        <h3 className="font-medium text-gray-900">AI Assistant</h3>
        <p className="text-xs text-gray-500 mt-1">Real-time session insights</p>
      </div>

      {/* High Risk Alert Banner */}
      {showHighRiskAlert && currentRisk && (
        <div className="bg-red-50 border-b-2 border-red-400 p-3 animate-pulse">
          <div className="flex items-start gap-2">
            <span className="text-red-600 text-lg">⚠️</span>
            <div className="flex-1">
              <div className="font-semibold text-red-800 text-sm mb-1">
                High Risk Detected!
              </div>
              <div className="text-xs text-red-700 mb-2">
                Risk Level: <span className="font-bold">{currentRisk.risk_level?.toUpperCase()}</span> ({currentRisk.risk_score}/10)
              </div>
              {currentRisk.recommendations && currentRisk.recommendations.length > 0 && (
                <div className="text-xs text-red-700">
                  <strong>Action:</strong> {currentRisk.recommendations[0]}
                </div>
              )}
              <button
                onClick={() => setShowHighRiskAlert(false)}
                className="mt-2 text-xs text-red-600 hover:text-red-800 underline"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Current Analysis */}
      <div className="p-4 border-b border-gray-100 space-y-3">
        <div>
          <h4 className="text-sm font-medium text-gray-700 mb-2">Current Session</h4>
          
          {analysisLoading ? (
            <div className="text-xs text-gray-500">🔄 Analyzing...</div>
          ) : (
            <div className="space-y-2">
              {currentTone && (
                <div>
                  <span className="text-xs text-gray-600">Latest Tone:</span>
                  <div className="mt-1">
                    <ToneIndicator tone={currentTone.tone} intensity={currentTone.intensity} />
                  </div>
                </div>
              )}
              
              {currentRisk && (
                <div>
                  <span className="text-xs text-gray-600">Risk Level:</span>
                  <div className="mt-1">
                    <RiskIndicator level={currentRisk.risk_level} score={currentRisk.risk_score} />
                  </div>
                </div>
              )}

              {currentRisk?.recommendations && currentRisk.recommendations.length > 0 && (
                <div className="mt-2">
                  <span className="text-xs text-gray-600">Recommendations:</span>
                  <ul className="text-xs text-gray-700 mt-1 space-y-1">
                    {currentRisk.recommendations.slice(0, 2).map((rec, idx) => (
                      <li key={idx} className="flex items-start">
                        <span className="text-blue-500 mr-1">•</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Rephrase Tool */}
      <div className="p-4 border-b border-gray-100">
        <h4 className="text-sm font-medium text-gray-700 mb-2">Tone Coach</h4>
        <div className="space-y-2">
          <textarea
            value={rephraseText}
            onChange={(e) => setRephraseText(e.target.value)}
            placeholder="Enter text to get neutral rephrasing suggestions..."
            className="w-full p-2 text-xs border border-gray-300 rounded resize-none"
            rows={3}
          />
          <button
            onClick={handleRephraseRequest}
            disabled={!rephraseText.trim() || loading}
            className="w-full py-1 px-2 bg-blue-600 text-white text-xs rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? 'Getting suggestion...' : 'Get Suggestion'}
          </button>
          
          {rephraseSuggestion && (
            <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded">
              <div className="text-xs text-green-800 mb-1">Suggested:</div>
              <div className="text-xs text-green-900 mb-2">{rephraseSuggestion.suggested}</div>
              <div className="flex gap-1">
                <button
                  onClick={handleUseSuggestion}
                  className="text-xs bg-green-600 text-white px-2 py-1 rounded hover:bg-green-700"
                >
                  Use This
                </button>
                <button
                  onClick={() => setRephraseSuggestion(null)}
                  className="text-xs text-gray-600 px-2 py-1 hover:text-gray-800"
                >
                  Dismiss
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Auto-Generated Insights */}
      <div className="flex-1 overflow-y-auto">
        <div className="p-4">
          <h4 className="text-sm font-medium text-gray-700 mb-3 flex items-center gap-2">
            <span>Recent AI Analysis</span>
            {autoInsights.length > 0 && (
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                {autoInsights.length} insights
              </span>
            )}
          </h4>
          
          {autoInsights.length === 0 ? (
            <div className="text-xs text-gray-500 italic">
              AI will automatically analyze messages as they arrive...
            </div>
          ) : (
            <div className="space-y-3">
              {autoInsights.slice(0, 5).map((insight) => (
                <div 
                  key={insight.id} 
                  className="p-3 bg-gray-50 border border-gray-200 rounded text-xs"
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-medium text-gray-900">
                      {insight.insight_type === 'tone_analysis' && '🎭 Tone Analysis'}
                      {insight.insight_type === 'risk_assessment' && '⚠️ Risk Assessment'}
                      {insight.insight_type === 'summary' && '📝 Summary'}
                    </span>
                    <span className="text-gray-500">
                      {new Date(insight.created_at).toLocaleTimeString([], { 
                        hour: '2-digit', 
                        minute: '2-digit' 
                      })}
                    </span>
                  </div>
                  
                  {/* Tone Analysis Display */}
                  {insight.insight_type === 'tone_analysis' && insight.content && (
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <ToneIndicator 
                          tone={insight.content.tone} 
                          intensity={insight.content.intensity} 
                        />
                      </div>
                      {insight.content.suggestions && insight.content.suggestions.length > 0 && (
                        <div className="mt-2 text-gray-700">
                          <strong>Suggestions:</strong>
                          <ul className="ml-3 mt-1 space-y-1">
                            {insight.content.suggestions.slice(0, 2).map((sug, idx) => (
                              <li key={idx}>• {sug}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                  
                  {/* Risk Assessment Display */}
                  {insight.insight_type === 'risk_assessment' && insight.content && (
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <RiskIndicator 
                          level={insight.content.risk_level} 
                          score={insight.content.risk_score} 
                        />
                      </div>
                      {insight.content.indicators && insight.content.indicators.length > 0 && (
                        <div className="mt-2 text-gray-700">
                          <strong>Indicators:</strong> {insight.content.indicators.join(', ')}
                        </div>
                      )}
                      {insight.content.recommendations && insight.content.recommendations.length > 0 && (
                        <div className="mt-2 text-gray-700">
                          <strong>Actions:</strong>
                          <ul className="ml-3 mt-1 space-y-1">
                            {insight.content.recommendations.slice(0, 2).map((rec, idx) => (
                              <li key={idx}>• {rec}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="p-3 bg-red-50 border-t border-red-200">
          <div className="text-xs text-red-700">⚠️ {error}</div>
        </div>
      )}
    </div>
  );
}