import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import DashboardFrame from '../../components/DashboardFrame';
import { Card, CardHeader, CardTitle, CardContent, CardDecoration } from '../../components/ui/card-enhanced';
import { useAuth } from '../../context/AuthContext';
import { API_BASE_URL, API_ENDPOINTS, getAuthHeaders } from '../../config/api';
import { FileText, Download, Save, Eye, AlertCircle, CheckCircle, ArrowLeft } from 'lucide-react';
import AIInsightsPanel from '../../components/ai/AIInsightsPanel';

export default function DraftReport() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [cases, setCases] = useState([]);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(null);
  const [preview, setPreview] = useState(false);
  
  const [formData, setFormData] = useState({
    caseId: '',
    reportType: 'mediation_summary',
    title: '',
    content: '',
    recommendations: '',
    nextSteps: ''
  });

  useEffect(() => {
    fetchCases();
  }, [user]);

  const fetchCases = async () => {
    if (!user?.user_id) return;
    
    try {
      const headers = getAuthHeaders();
      const response = await fetch(`${API_BASE_URL}${API_ENDPOINTS.cases.list(user.user_id)}`, { headers });
      const data = await response.json();
      
      if (data.cases) {
        setCases(data.cases);
        if (data.cases.length > 0 && !formData.caseId) {
          setFormData(prev => ({ ...prev, caseId: data.cases[0].id }));
        }
      }
    } catch (err) {
      console.error('Error fetching cases:', err);
    }
  };

  const handleSaveDraft = async () => {
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const headers = getAuthHeaders();

      // Save to case notes for now (you can create a dedicated reports table later)
      const response = await fetch(`${API_BASE_URL}${API_ENDPOINTS.cases.notes(formData.caseId)}`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          note_type: 'report',
          content: JSON.stringify(formData),
          title: formData.title || 'Draft Report'
        })
      });

      if (response.ok) {
        setSuccess(true);
        setTimeout(() => setSuccess(false), 5000);
      } else {
        const data = await response.json();
        setError(data.error?.message || 'Failed to save report');
      }
    } catch (err) {
      setError('Network error. Please try again.');
      console.error('Save error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    // Generate simple text format for download
    const reportText = `
MEDIATION REPORT
${formData.reportType === 'mediation_summary' ? 'Mediation Summary' : 'Progress Report'}

Title: ${formData.title}
Date: ${new Date().toLocaleDateString()}
Mediator: ${user.name || user.email}

SUMMARY
${formData.content}

RECOMMENDATIONS
${formData.recommendations}

NEXT STEPS
${formData.nextSteps}

---
Generated by MediationApp
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${formData.title.replace(/\s+/g, '_') || 'report'}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  return (
    <DashboardFrame title="Draft Report">
      {/* Back Button */}
      <div className="mb-4">
        <button
          onClick={() => navigate('/mediator')}
          className="
            inline-flex items-center gap-2 px-4 py-2 rounded-lg
            bg-slate-800/50 border border-slate-700
            text-slate-300 hover:text-teal-400
            hover:border-teal-500/50
            transition-all duration-200
          "
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </button>
      </div>

      <div className="max-w-5xl mx-auto">
        {success && (
          <div className="mb-6 p-4 bg-green-500/20 border border-green-500/30 rounded-lg flex items-start gap-3">
            <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
            <div>
              <div className="font-medium text-green-300">Report Saved!</div>
              <div className="text-sm text-green-400/80 mt-1">Your draft has been saved to the case notes.</div>
            </div>
          </div>
        )}

        {error && (
          <div className="mb-6 p-4 bg-red-500/20 border border-red-500/30 rounded-lg flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div>
              <div className="font-medium text-red-300">Error</div>
              <div className="text-sm text-red-400/80 mt-1">{error}</div>
            </div>
          </div>
        )}

        <Card gradient>
          <CardDecoration color="purple" />
          <CardHeader icon={<FileText className="w-5 h-5 text-purple-400" />}>
            <CardTitle>Create Mediation Report</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {/* Case and Type Selection */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-2 text-slate-300">
                    Select Case *
                  </label>
                  <select
                    name="caseId"
                    value={formData.caseId}
                    onChange={handleChange}
                    required
                    className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                      text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="">Choose a case...</option>
                    {cases.map(c => (
                      <option key={c.id} value={c.id}>
                        {c.title || c.description || `Case #${c.id.slice(0, 8)}`}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-slate-300">
                    Report Type *
                  </label>
                  <select
                    name="reportType"
                    value={formData.reportType}
                    onChange={handleChange}
                    className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                      text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="mediation_summary">Mediation Summary</option>
                    <option value="progress_report">Progress Report</option>
                    <option value="final_report">Final Report</option>
                    <option value="session_notes">Session Notes</option>
                  </select>
                </div>
              </div>

              {/* Title */}
              <div>
                <label className="block text-sm font-medium mb-2 text-slate-300">
                  Report Title *
                </label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleChange}
                  required
                  placeholder="e.g., Mediation Session 1 - Initial Discussion"
                  className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                    text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
                />
              </div>

              {/* Main Content */}
              <div>
                <label className="block text-sm font-medium mb-2 text-slate-300">
                  Summary / Key Points *
                </label>
                <textarea
                  name="content"
                  value={formData.content}
                  onChange={handleChange}
                  rows={8}
                  required
                  placeholder="Summarize the mediation session, key discussions, agreements reached, and any concerns..."
                  className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                    text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                />
              </div>

              {/* Recommendations */}
              <div>
                <label className="block text-sm font-medium mb-2 text-slate-300">
                  Recommendations
                </label>
                <textarea
                  name="recommendations"
                  value={formData.recommendations}
                  onChange={handleChange}
                  rows={4}
                  placeholder="Recommended actions, areas for further discussion, or suggested solutions..."
                  className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                    text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                />
              </div>

              {/* Next Steps */}
              <div>
                <label className="block text-sm font-medium mb-2 text-slate-300">
                  Next Steps
                </label>
                <textarea
                  name="nextSteps"
                  value={formData.nextSteps}
                  onChange={handleChange}
                  rows={4}
                  placeholder="Action items, follow-up tasks, scheduled next session, documents needed..."
                  className="w-full px-4 py-2.5 bg-slate-800/50 border border-slate-700 rounded-lg 
                    text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                />
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-3 pt-4 border-t border-slate-700">
                <button
                  type="button"
                  onClick={handleSaveDraft}
                  disabled={loading || !formData.caseId || !formData.title || !formData.content}
                  className="flex-1 px-6 py-3 bg-gradient-to-r from-purple-500 to-blue-500 text-white font-medium rounded-lg
                    hover:from-purple-600 hover:to-blue-600 disabled:opacity-50 disabled:cursor-not-allowed
                    transition-all flex items-center justify-center gap-2"
                >
                  {loading ? (
                    <>
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Saving...
                    </>
                  ) : (
                    <>
                      <Save className="w-5 h-5" />
                      Save Draft
                    </>
                  )}
                </button>
                
                <button
                  type="button"
                  onClick={handleExport}
                  disabled={!formData.title || !formData.content}
                  className="px-6 py-3 bg-slate-700 text-white font-medium rounded-lg
                    hover:bg-slate-600 disabled:opacity-50 disabled:cursor-not-allowed
                    transition-all flex items-center gap-2"
                >
                  <Download className="w-5 h-5" />
                  Export
                </button>

                <button
                  type="button"
                  onClick={() => setPreview(!preview)}
                  className="px-6 py-3 bg-slate-700 text-white font-medium rounded-lg
                    hover:bg-slate-600 transition-all flex items-center gap-2"
                >
                  <Eye className="w-5 h-5" />
                  {preview ? 'Hide' : 'Preview'}
                </button>

                <button
                  type="button"
                  onClick={() => navigate(-1)}
                  className="px-6 py-3 bg-slate-800 border border-slate-700 text-slate-300 font-medium rounded-lg
                    hover:bg-slate-700 transition-all"
                >
                  Cancel
                </button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Preview Section */}
        {preview && formData.content && (
          <Card gradient className="mt-6">
            <CardHeader icon={<Eye className="w-5 h-5 text-blue-400" />}>
              <CardTitle>Preview</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="prose prose-invert max-w-none">
                <h2 className="text-2xl font-bold text-white mb-2">{formData.title}</h2>
                <div className="text-sm text-slate-400 mb-6">
                  {new Date().toLocaleDateString()} • {user.name || user.email}
                </div>
                
                <div className="space-y-6">
                  <div>
                    <h3 className="text-lg font-semibold text-slate-200 mb-2">Summary</h3>
                    <div className="text-slate-300 whitespace-pre-wrap">{formData.content}</div>
                  </div>
                  
                  {formData.recommendations && (
                    <div>
                      <h3 className="text-lg font-semibold text-slate-200 mb-2">Recommendations</h3>
                      <div className="text-slate-300 whitespace-pre-wrap">{formData.recommendations}</div>
                    </div>
                  )}
                  
                  {formData.nextSteps && (
                    <div>
                      <h3 className="text-lg font-semibold text-slate-200 mb-2">Next Steps</h3>
                      <div className="text-slate-300 whitespace-pre-wrap">{formData.nextSteps}</div>
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardFrame>
  );
}
